# @format

_base_:
  - ../../base/mipnerf360.yaml
  - ../../base/2dts.yaml

experiment:
  name: 2dts_garden

dataset:
  scene: garden
  image_dir: images_4
  resolution: 1

d2ts:
  native_config: configs/2dts/native/mipnerf360.yaml
  target_point_num: 3000000
